/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookSlotRouteImport } from './routes/book.slot'
import { Route as BookOutOfAreaRouteImport } from './routes/book.out-of-area'
import { Route as BookConfirmedRouteImport } from './routes/book.confirmed'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSlotsRouteImport } from './routes/_authenticated/admin.slots'
import { Route as AuthenticatedAdminPincodesRouteImport } from './routes/_authenticated/admin.pincodes'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlotRoute = BookSlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => BookRoute,
} as any)
const BookOutOfAreaRoute = BookOutOfAreaRouteImport.update({
  id: '/out-of-area',
  path: '/out-of-area',
  getParentRoute: () => BookRoute,
} as any)
const BookConfirmedRoute = BookConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => BookRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSlotsRoute = AuthenticatedAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPincodesRoute =
  AuthenticatedAdminPincodesRouteImport.update({
    id: '/pincodes',
    path: '/pincodes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/out-of-area': typeof BookOutOfAreaRoute
  '/book/slot': typeof BookSlotRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/pincodes': typeof AuthenticatedAdminPincodesRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/out-of-area': typeof BookOutOfAreaRoute
  '/book/slot': typeof BookSlotRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/pincodes': typeof AuthenticatedAdminPincodesRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/out-of-area': typeof BookOutOfAreaRoute
  '/book/slot': typeof BookSlotRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/pincodes': typeof AuthenticatedAdminPincodesRoute
  '/_authenticated/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/sitemap.xml'
    | '/admin'
    | '/book/confirmed'
    | '/book/out-of-area'
    | '/book/slot'
    | '/admin/bookings'
    | '/admin/leads'
    | '/admin/pincodes'
    | '/admin/slots'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/sitemap.xml'
    | '/book/confirmed'
    | '/book/out-of-area'
    | '/book/slot'
    | '/admin/bookings'
    | '/admin/leads'
    | '/admin/pincodes'
    | '/admin/slots'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/book/confirmed'
    | '/book/out-of-area'
    | '/book/slot'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/pincodes'
    | '/_authenticated/admin/slots'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/slot': {
      id: '/book/slot'
      path: '/slot'
      fullPath: '/book/slot'
      preLoaderRoute: typeof BookSlotRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/out-of-area': {
      id: '/book/out-of-area'
      path: '/out-of-area'
      fullPath: '/book/out-of-area'
      preLoaderRoute: typeof BookOutOfAreaRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/confirmed': {
      id: '/book/confirmed'
      path: '/confirmed'
      fullPath: '/book/confirmed'
      preLoaderRoute: typeof BookConfirmedRouteImport
      parentRoute: typeof BookRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slots': {
      id: '/_authenticated/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AuthenticatedAdminSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pincodes': {
      id: '/_authenticated/admin/pincodes'
      path: '/pincodes'
      fullPath: '/admin/pincodes'
      preLoaderRoute: typeof AuthenticatedAdminPincodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminPincodesRoute: typeof AuthenticatedAdminPincodesRoute
  AuthenticatedAdminSlotsRoute: typeof AuthenticatedAdminSlotsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminPincodesRoute: AuthenticatedAdminPincodesRoute,
  AuthenticatedAdminSlotsRoute: AuthenticatedAdminSlotsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BookRouteChildren {
  BookConfirmedRoute: typeof BookConfirmedRoute
  BookOutOfAreaRoute: typeof BookOutOfAreaRoute
  BookSlotRoute: typeof BookSlotRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookConfirmedRoute: BookConfirmedRoute,
  BookOutOfAreaRoute: BookOutOfAreaRoute,
  BookSlotRoute: BookSlotRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
